export type ProductItem = {
  id: string;
  title: string;
  summary: string;
  category: string;
  tags: string[];
  thumbnail: string; // URL or gradient
  colSpan: number; // 1-4
  rowSpan: number; // 1-4
  gradient: string;
  year: string;
};

export const CATEGORIES = [
  "All",
  "Web Design",
  "Branding",
  "Development",
  "UI/UX",
  "Creative",
  "Photography",
] as const;

export const PRODUCT_ITEMS: ProductItem[] = [
  {
    id: "alpha",
    title: "Project Alpha",
    summary: "A bold reimagining of digital storytelling through interactive design.",
    category: "Web Design",
    tags: ["Design", "Frontend", "Interactive"],
    thumbnail: "",
    colSpan: 4,
    rowSpan: 3,
    gradient: "linear-gradient(135deg, #14A8C7 0%, #273582 100%)",
    year: "2025",
  },
  {
    id: "beta",
    title: "Project Beta",
    summary: "Visual identity system that bridges tradition and modernity.",
    category: "Branding",
    tags: ["Branding", "Identity", "Print"],
    thumbnail: "",
    colSpan: 2,
    rowSpan: 2,
    gradient: "linear-gradient(135deg, #AC5D7B 0%, #273582 100%)",
    year: "2025",
  },
  {
    id: "gamma",
    title: "Project Gamma",
    summary: "Full-stack application built for scale and elegance.",
    category: "Development",
    tags: ["React", "Node.js", "Full-stack"],
    thumbnail: "",
    colSpan: 3,
    rowSpan: 2,
    gradient: "linear-gradient(135deg, #8099B2 0%, #14A8C7 100%)",
    year: "2024",
  },
  {
    id: "delta",
    title: "Project Delta",
    summary: "Experience design focused on delight, usability, and craft.",
    category: "UI/UX",
    tags: ["UX", "Prototype", "Research"],
    thumbnail: "",
    colSpan: 3,
    rowSpan: 3,
    gradient: "linear-gradient(135deg, #273582 0%, #AC5D7B 100%)",
    year: "2024",
  },
  {
    id: "epsilon",
    title: "Project Epsilon",
    summary: "A creative exploration of motion and generative art.",
    category: "Creative",
    tags: ["Motion", "Generative", "Canvas"],
    thumbnail: "",
    colSpan: 2,
    rowSpan: 2,
    gradient: "linear-gradient(160deg, #14A8C7 0%, #AC5D7B 60%, #273582 100%)",
    year: "2024",
  },
  {
    id: "zeta",
    title: "Project Zeta",
    summary: "Minimal brand language for a luxury skincare line.",
    category: "Branding",
    tags: ["Branding", "Luxury", "Packaging"],
    thumbnail: "",
    colSpan: 2,
    rowSpan: 3,
    gradient: "linear-gradient(135deg, #F0ECEE 0%, #8099B2 50%, #273582 100%)",
    year: "2023",
  },
  {
    id: "eta",
    title: "Project Eta",
    summary: "Photography series capturing urban architecture at golden hour.",
    category: "Photography",
    tags: ["Photography", "Urban", "Architecture"],
    thumbnail: "",
    colSpan: 4,
    rowSpan: 2,
    gradient: "linear-gradient(135deg, #AC5D7B 0%, #F0ECEE 40%, #8099B2 100%)",
    year: "2023",
  },
  {
    id: "theta",
    title: "Project Theta",
    summary: "Interactive data visualization dashboard for climate insights.",
    category: "Development",
    tags: ["D3.js", "Data", "Visualization"],
    thumbnail: "",
    colSpan: 3,
    rowSpan: 2,
    gradient: "linear-gradient(135deg, #8099B2 0%, #273582 60%, #14A8C7 100%)",
    year: "2023",
  },
  {
    id: "iota",
    title: "Project Iota",
    summary: "E-commerce experience redesign with focus on accessibility.",
    category: "UI/UX",
    tags: ["E-commerce", "Accessibility", "Figma"],
    thumbnail: "",
    colSpan: 2,
    rowSpan: 2,
    gradient: "linear-gradient(135deg, #14A8C7 0%, #F0ECEE 100%)",
    year: "2023",
  },
  {
    id: "kappa",
    title: "Project Kappa",
    summary: "Typographic experiments blending heritage serifs with modern geometry.",
    category: "Creative",
    tags: ["Typography", "Experimental", "Print"],
    thumbnail: "",
    colSpan: 3,
    rowSpan: 2,
    gradient: "linear-gradient(135deg, #273582 0%, #8099B2 50%, #AC5D7B 100%)",
    year: "2022",
  },
  {
    id: "lambda",
    title: "Project Lambda",
    summary: "An editorial website for a contemporary art magazine.",
    category: "Web Design",
    tags: ["Editorial", "CMS", "Design"],
    thumbnail: "",
    colSpan: 2,
    rowSpan: 3,
    gradient: "linear-gradient(160deg, #AC5D7B 0%, #14A8C7 100%)",
    year: "2022",
  },
  {
    id: "mu",
    title: "Project Mu",
    summary: "Mobile-first social platform for independent musicians.",
    category: "Development",
    tags: ["React Native", "API", "Social"],
    thumbnail: "",
    colSpan: 4,
    rowSpan: 2,
    gradient: "linear-gradient(135deg, #273582 0%, #14A8C7 40%, #8099B2 100%)",
    year: "2022",
  },
];
